spring:
  profiles:
    active: dev
  config:
    import: optional:secrets.yaml

---

spring:
  application:
    name: crm-orders
  config:
    activate:
      on-profile: dev
    import: configserver:http://localhost:3500
  cloud:
    config:
      fail-fast: true
      name: "crm-orders"
  data:
  datasource:
    url: jdbc:postgresql://localhost:3506/crm_orders?currentSchema=public
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    validate-migration-naming: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public
server:
  port: 3503
  servlet:
    context-path: /api
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
logging:
  file:
    name: log.txt
  level:
    org:
      springframework: info
      hibernate:
        type: trace
app:
  all-methods-log:
    enabled: true
springdoc:
  show-actuator: true
management:
  server:
    port: 9090
feign:
  client:
    config:
      crm-customers-microservice:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        decode404: false
restclient:
  crm-customers-microservice:
    name: crm-customers
    basepath: /api/v1/customers


